### ISSUE TITLE
Failure to install: conda env not created and openmpi compilation issues.

### ISSUE THREAD

**Issue by jmp75** [awracms/awra_cms#2]
I am trying to install AWRA-CMS on a Linux cluster as of 2023-05-19, as per instructions with `curl -s https://raw.githubusercontent.com/awracms/awra_cms/AWRA_CMS_v1.2/scripts/install.sh | bash`.  The conda env fails to create but the script does not notice this and continues for a few steps.

```text
[CONDA] Creating miniconda environment
[..]
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - anaconda::pandas=0.19
  - anaconda::cffi=1.9

[CONDA] Conda environment has been created

```

Also, the opal wrappers for openmpi fail to link: `make[2]: *** [Makefile:1877: opal_wrapper] Error 1` `make[2]: *** [Makefile:1877: opal_wrapper] Error 1`

While conda channels are supposed to be backward compatible, `pandas=0.19` is probably an issue by now. I'll see if I can diagnose a bit further why conda fails to resolve dependencies. I'll initiate a PR if I can find a small fix i.e. not a full upgrade to the latest pandas if I had a guess.

**Comment by jmp75** [comment]
At the least there is an issue with `  - anaconda::cffi=1.9.*`  in the conda env specification file. 

`mamba search -c anaconda cffi` does not return any version 1.9.x as I write.

**Comment by jmp75** [comment]
I tried to gradually relax some of the version constraints for the conda environment, but to no avail.

`mamba` was taking quite some minutes trying to solve the environment (conda would likely take even longer), but it was still not solvable, e.g. with diagnostics such as:

```
Encountered problems while solving:
  - package gdal-2.4.4-py36hbb8311d_1 requires numpy >=1.14.6,<2.0a0, but none of the providers can be installed
```

I could create a conda environment only by removing all version constraints. I've no idea if there are hidden breaking changes at runtime though.

```yaml
---
name: awra-cms
channels:
  - conda-forge
dependencies:
  - nose
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - pandas
  - h5py
  - cffi
  - libnetcdf
  - netcdf4
  - libgdal
  - gdal
  # - mpi4py # available in conda-forge. May work.
  - notebook
  - tornado
  - dask
  - seaborn
  - basemap
  - cartopy
  - xarray
  - paramiko
  - coverage
  - pip
  - pip:
    - SALib
    - safety
    - msgpack==0.6.0
    - pyDOE
```
